// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASV-0rTB8xGZYPNvNvvkJvrDA6kNkM4UE',
    appId: '1:766956126566:web:7ca8748fb91c1a197048a7',
    messagingSenderId: '766956126566',
    projectId: 'coinly-egypt',
    authDomain: 'coinly-egypt.firebaseapp.com',
    storageBucket: 'coinly-egypt.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJbeXGTSNxGg2JCrom8YEsZsHDt05S_XI',
    appId: '1:766956126566:android:ec1856ed80578e1b7048a7',
    messagingSenderId: '766956126566',
    projectId: 'coinly-egypt',
    storageBucket: 'coinly-egypt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnzwRw2-To_StY_ffhqUPbhs5fOOsMOXE',
    appId: '1:766956126566:ios:616dea6266490e367048a7',
    messagingSenderId: '766956126566',
    projectId: 'coinly-egypt',
    storageBucket: 'coinly-egypt.firebasestorage.app',
    iosBundleId: 'com.coinly.owner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnzwRw2-To_StY_ffhqUPbhs5fOOsMOXE',
    appId: '1:766956126566:ios:02a66968e5d44ef47048a7',
    messagingSenderId: '766956126566',
    projectId: 'coinly-egypt',
    storageBucket: 'coinly-egypt.firebasestorage.app',
    iosBundleId: 'com.coinly.owner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASV-0rTB8xGZYPNvNvvkJvrDA6kNkM4UE',
    appId: '1:766956126566:web:2caab7a867b21a287048a7',
    messagingSenderId: '766956126566',
    projectId: 'coinly-egypt',
    authDomain: 'coinly-egypt.firebaseapp.com',
    storageBucket: 'coinly-egypt.firebasestorage.app',
  );
}
